{{- if and .Values.stack.name .Values.stack.apply }}
apiVersion: v1
kind: Secret
metadata:
  name: stack-{{ .Values.stack.name }}
  labels:
    {{- include "gravity-init.labels" . | nindent 4 }}
data:
  values.yaml: {{ toYaml .Values.stack | b64enc }}
{{- end }}
