{{- if eq "helm" .Values.tls.genBy }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "gravity-init.fullname" . }}-tls
  labels:
    {{- include "gravity-init.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "gravity-init.gen-certs" . ) | indent 2 }}
{{- end }}
