{{- if and .Values.stack.apply (ne .Values.license "") }}
apiVersion: v1
kind: Secret
metadata:
  name: gravity-stack
  labels:
    {{- include "gravity-init.labels" . | nindent 4 }}
data:
  values.yaml: {{ toYaml .Values.stack | b64enc }}
{{- end }}
