apiVersion: v1
kind: Service
metadata:
  name: {{ include "gravity-init.fullname" . }}
  labels:
    {{- include "gravity-init.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.tls.enabled }}
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "gravity-init.selectorLabels" . | nindent 4 }}
