{{- if and .Values.rbac.enabled (not .Values.rbac.namespaced) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gravity-init.fullname" . }}
  labels:
    {{- include "gravity-init.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gravity-init.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "gravity-init.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
