{{- if and .Values.rbac.enabled .Values.rbac.namespaced -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gravity-init.fullname" . }}
  labels:
    {{- include "gravity-init.labels" . | nindent 4 }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
  - verbs:
      - '*'
    nonResourceURLs:
      - '*'
{{- end -}}
